# metadata
MODEL_NAME = "prototype_5.npz"

# hyperparameters for the neural network
LAYER_DIMS = [784, 128, 10]
INPUT_UNITS = LAYER_DIMS[0]
HIDDEN_UNITS = sum(LAYER_DIMS[1:-1])
OUTPUT_UNITS = LAYER_DIMS[-1]

LEARNING_RATE = 0.01
BATCH_SIZE = 64
EPOCHS = 75

# app
SIDEBAR_WIDTH = 200
SCALAR = 28
SQUARE = 25
HEIGHT = SCALAR * SQUARE
WIDTH = HEIGHT + SIDEBAR_WIDTH

COLOUR_BOARD_LIGHT = "#597e8b"
COLOUR_BOARD_DARK = "#416b7a"
COLOUR_PEN = "#000000"
COLOUR_BACKGROUND = "#124659"

PREDICTION_TEXT_SIZE = 50
PREDICTION_TEXT_COLOUR = "#FFFFFF"
PREDICTION_TEXT_COORDINATES = (WIDTH // 2 + 340, HEIGHT // 2 - 40)